apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-worker
  namespace: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-worker
  template:
    metadata:
      labels:
        app: sms-worker
    spec:
      containers:
        - name: sms-worker
          image: torment93/ns-notifications-smsworker:latest
          imagePullPolicy: Always
          env:
            - name: RabbitMq__Host
              value: rabbitmq
            - name: RabbitMq__Port
              value: "5672"
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
